export const GET_PROJECTS_START = 'GET_PROJECTS_START'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR'

export const GET_ACTIVE_CONNECTION_SUCCESS = 'GET_ACTIVE_CONNECTION_SUCCESS'
export const SWITCH_TO_ACTIVE_CONNECTION = 'SWITCH_TO_ACTIVE_CONNECTION'


export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'

export const CHANGE_ROLE = 'CHANGE_ROLE'
export const MARKING_TYPE_CLICK = 'MARKING_TYPE_CLICK'
export const RESET_MARKTYPE = 'RESET_MARKTYPE'
export const COMPLETE_DATE_AUTHOR = 'COMPLETE_DATE_AUTHOR'
export const RESET_COMPLETE_DATE_AUTHOR = 'RESET_COMPLETE_DATE_AUTHOR'

export const POST_PROJECT_START = 'POST_PROJECT_START'
export const POST_PROJECT_SUCCESS = 'POST_PROJECT_SUCCESS'